FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    build-essential \
    devscripts \
    fakeroot \
    cmake \
    make \
    gcc \
    locales \
    libssl-dev \
    libxslt-dev \
    libxml2-dev \
    libxerces-c-dev

RUN dpkg-reconfigure locales && \
    locale-gen en_US.UTF-8 && \
    /usr/sbin/update-locale LANG=en_US.UTF-8

RUN git clone https://github.com/cinecert/asdcplib.git /tmp/asdcplib \
    && cd /tmp/asdcplib \
    && mkdir build && cd build \
    && cmake .. \
    && make -j && make install \
    && rm -rf /tmp/asdcplib

ENV LC_ALL en_US.UTF-8

CMD asdcp-info -i -H -c -d /dcp/ECL01-SINGLE-CPL_TST_S_EN-XX_UK-U_71_2K_DI_20171218_ECL_IOP_OV/ECL01-SINGLE-CPL_TST_S_EN-XX_UK-U_71_2K_DI_20171218_ECL_IOP_OV_01.mxf
