FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    build-essential \
    devscripts \
    fakeroot \
    make \
    gcc \
    locales \
    git \
    cmake

RUN dpkg-reconfigure locales && \
    locale-gen en_US.UTF-8 && \
    /usr/sbin/update-locale LANG=en_US.UTF-8

RUN apt-get install -y libxerces-c-dev libssl-dev && \
    git clone https://github.com/cinecert/asdcplib.git && \
    cd asdcplib && mkdir build && cd build && \
    cmake .. && make -j && make install

RUN apt-get install -y mediainfo sox

RUN apt-get install -y --no-install-recommends \
    python3 \
    python3-dev \
    python3-pip && \
    pip3 install -U pip setuptools

ENV LC_ALL en_US.UTF-8

CMD pip3 install pipenv && \
    git clone https://github.com/Ymagis/ClairMeta.git && \
    cd ClairMeta && pipenv install --dev --skip-lock && \
    ln -s /resources tests/resources && \
    pipenv run nosetests --nocapture --with-doctest --doctest-options=+ELLIPSIS --with-coverage --cover-package=clairmeta -v