FROM ubuntu:trusty

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    dput \
    curl \
    wget \
    libxml2-dev \
    build-essential \
    devscripts \
    fakeroot \
    make \
    gcc \
    locales \
    debhelper \
    python \
    python-dev \
    python-pip \
    python-all \
    python-setuptools \
    python-all-dev

# Update to Python 3.6 (default is stuck to 3.4)
# Pipenv require 3.5+ to properly work
RUN apt-get install -y software-properties-common \
    && add-apt-repository ppa:jonathonf/python-3.6 \
    && apt-get update \
    && apt-get install -y python3.6 python3.6-dev \
    && wget https://bootstrap.pypa.io/get-pip.py && python3.6 get-pip.py \
    && rm /usr/bin/python3 \
    && ln -s python3.6 /usr/bin/python3 \
    && ln -s /usr/local/bin/pip /usr/bin/pip3

RUN dpkg-reconfigure locales && \
    locale-gen en_US.UTF-8 && \
    /usr/sbin/update-locale LANG=en_US.UTF-8

RUN apt-get update && apt-get install -y \
    apt-transport-https \
    libffi-dev \
    autotools-dev \
    libssl-dev \
    lintian

RUN pip3 install -U pip setuptools

ENV LC_ALL en_US.UTF-8

CMD cd /build_src && ./build_deb.sh